[package]
name = "biographer"
version = "0.1.0"
authors = ["Marshall Bowers <elliott.codes@gmail.com>"]
edition = "2018"

[dependencies]
chrono = "0.4.38"
console = "0.8"
dialoguer = "0.4"
femme = "1.2"
indicatif = "0.11"
log = "0.4"
